version: '4.71.0'

services:

  db-test:
    image: postgres:18.2
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro-test

  cache-test:
    image: redis:8.6.3-alpine
    restart: always
    ports:
      - '6380:6379'
